spring:
  datasource:
    username: admin_residence
    password: 4dm1nR3s
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staffmanagement

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 4444

